version: '3.4'

services:
  googlebooksfuture:
    image: googlebooksfuture
    build:
      context: .
      # dockerfile: ./Dockerfile
    container_name: google-books_C2
    entrypoint: /bin/sh
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    tty: true

